name: farm-flow

services:
  mysql:
    image: mysql:8.0
    container_name: farm-flow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: farm-flow
      TZ: UTC
    volumes:
      - .docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - .docker/mysql/data:/var/lib/mysql
      - .docker/mysql/log:/var/log
    ports:
      - 33065:3306
    restart: unless-stopped
    networks:
      - farm-flow

networks:
  farm-flow:
    driver: bridge
