server:
  port: 4000

cors:
  allowed-origin-patterns:
    - "http://localhost:*"
    - "http://127.0.0.1:*"
    - "http://192.168.0.*:*"
    - "http://172.*.*.*:*"
    
spring:
  application:
    name: farm-flow

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33065/farm-flow
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: dHJvdWJsZXNvbWUtYWRtaW4tYXBpLXNlcnZlci1qc29ud2VidG9rZW4tYWNjZXNzLXRva2VuLXNlY3JldA==
  expiration-seconds: 86400
